version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./marketplace.db
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=Admin123!
      - ADMIN_EMAIL=admin@example.com
    volumes:
      - ./uploads:/app/uploads
      - ./marketplace.db:/app/marketplace.db 